// <auto-generated />
namespace NurseryApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class nurserymentrees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nurserymentrees));
        
        string IMigrationMetadata.Id
        {
            get { return "202302111948223_nurserymen-trees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
